# Generated by Django 3.2.4 on 2021-06-15 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Quarto',
        ),
    ]
